# Generated by Django 4.0.5 on 2022-06-18 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='due',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
